# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from estimate_interest/PersonInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class PersonInfo(genpy.Message):
  _md5sum = "e4b2c17bf05b415b48cf7ca9d72fa1ad"
  _type = "estimate_interest/PersonInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 person_id
uint8 status
time stamp
float64 x
float64 y
float64 z"""
  __slots__ = ['person_id','status','stamp','x','y','z']
  _slot_types = ['uint8','uint8','time','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       person_id,status,stamp,x,y,z

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PersonInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.person_id is None:
        self.person_id = 0
      if self.status is None:
        self.status = 0
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
    else:
      self.person_id = 0
      self.status = 0
      self.stamp = genpy.Time()
      self.x = 0.
      self.y = 0.
      self.z = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B2I3d().pack(_x.person_id, _x.status, _x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 34
      (_x.person_id, _x.status, _x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.z,) = _get_struct_2B2I3d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B2I3d().pack(_x.person_id, _x.status, _x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 34
      (_x.person_id, _x.status, _x.stamp.secs, _x.stamp.nsecs, _x.x, _x.y, _x.z,) = _get_struct_2B2I3d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B2I3d = None
def _get_struct_2B2I3d():
    global _struct_2B2I3d
    if _struct_2B2I3d is None:
        _struct_2B2I3d = struct.Struct("<2B2I3d")
    return _struct_2B2I3d
