// Generated by gencpp from file estimate_interest/PersonInfo.msg
// DO NOT EDIT!


#ifndef ESTIMATE_INTEREST_MESSAGE_PERSONINFO_H
#define ESTIMATE_INTEREST_MESSAGE_PERSONINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace estimate_interest
{
template <class ContainerAllocator>
struct PersonInfo_
{
  typedef PersonInfo_<ContainerAllocator> Type;

  PersonInfo_()
    : person_id(0)
    , status(0)
    , stamp()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  PersonInfo_(const ContainerAllocator& _alloc)
    : person_id(0)
    , status(0)
    , stamp()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _person_id_type;
  _person_id_type person_id;

   typedef uint8_t _status_type;
  _status_type status;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::estimate_interest::PersonInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::estimate_interest::PersonInfo_<ContainerAllocator> const> ConstPtr;

}; // struct PersonInfo_

typedef ::estimate_interest::PersonInfo_<std::allocator<void> > PersonInfo;

typedef boost::shared_ptr< ::estimate_interest::PersonInfo > PersonInfoPtr;
typedef boost::shared_ptr< ::estimate_interest::PersonInfo const> PersonInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::estimate_interest::PersonInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::estimate_interest::PersonInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace estimate_interest

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'estimate_interest': ['/home/johs/prosjekt/temp_ws/src/estimate_interest/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::estimate_interest::PersonInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::estimate_interest::PersonInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estimate_interest::PersonInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estimate_interest::PersonInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estimate_interest::PersonInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estimate_interest::PersonInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::estimate_interest::PersonInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4b2c17bf05b415b48cf7ca9d72fa1ad";
  }

  static const char* value(const ::estimate_interest::PersonInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4b2c17bf05b415bULL;
  static const uint64_t static_value2 = 0x48cf7ca9d72fa1adULL;
};

template<class ContainerAllocator>
struct DataType< ::estimate_interest::PersonInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "estimate_interest/PersonInfo";
  }

  static const char* value(const ::estimate_interest::PersonInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::estimate_interest::PersonInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 person_id\n\
uint8 status\n\
time stamp\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::estimate_interest::PersonInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::estimate_interest::PersonInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.person_id);
      stream.next(m.status);
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::estimate_interest::PersonInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::estimate_interest::PersonInfo_<ContainerAllocator>& v)
  {
    s << indent << "person_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.person_id);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESTIMATE_INTEREST_MESSAGE_PERSONINFO_H
