// Generated by gencpp from file estimate_interest/PersonsArray.msg
// DO NOT EDIT!


#ifndef ESTIMATE_INTEREST_MESSAGE_PERSONSARRAY_H
#define ESTIMATE_INTEREST_MESSAGE_PERSONSARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <estimate_interest/PersonInfo.h>

namespace estimate_interest
{
template <class ContainerAllocator>
struct PersonsArray_
{
  typedef PersonsArray_<ContainerAllocator> Type;

  PersonsArray_()
    : persons()  {
    }
  PersonsArray_(const ContainerAllocator& _alloc)
    : persons(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::estimate_interest::PersonInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::estimate_interest::PersonInfo_<ContainerAllocator> >::other >  _persons_type;
  _persons_type persons;




  typedef boost::shared_ptr< ::estimate_interest::PersonsArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::estimate_interest::PersonsArray_<ContainerAllocator> const> ConstPtr;

}; // struct PersonsArray_

typedef ::estimate_interest::PersonsArray_<std::allocator<void> > PersonsArray;

typedef boost::shared_ptr< ::estimate_interest::PersonsArray > PersonsArrayPtr;
typedef boost::shared_ptr< ::estimate_interest::PersonsArray const> PersonsArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::estimate_interest::PersonsArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::estimate_interest::PersonsArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace estimate_interest

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'estimate_interest': ['/home/johs/prosjekt/temp_ws/src/estimate_interest/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::estimate_interest::PersonsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::estimate_interest::PersonsArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estimate_interest::PersonsArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::estimate_interest::PersonsArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estimate_interest::PersonsArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::estimate_interest::PersonsArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::estimate_interest::PersonsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17dc4f3d71f5a82ce376e93eda1f9791";
  }

  static const char* value(const ::estimate_interest::PersonsArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17dc4f3d71f5a82cULL;
  static const uint64_t static_value2 = 0xe376e93eda1f9791ULL;
};

template<class ContainerAllocator>
struct DataType< ::estimate_interest::PersonsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "estimate_interest/PersonsArray";
  }

  static const char* value(const ::estimate_interest::PersonsArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::estimate_interest::PersonsArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PersonInfo[] persons\n\
================================================================================\n\
MSG: estimate_interest/PersonInfo\n\
uint8 id\n\
time timestamp\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::estimate_interest::PersonsArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::estimate_interest::PersonsArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.persons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonsArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::estimate_interest::PersonsArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::estimate_interest::PersonsArray_<ContainerAllocator>& v)
  {
    s << indent << "persons[]" << std::endl;
    for (size_t i = 0; i < v.persons.size(); ++i)
    {
      s << indent << "  persons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::estimate_interest::PersonInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.persons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ESTIMATE_INTEREST_MESSAGE_PERSONSARRAY_H
